---
  - name: Update CentOS system
    sudo: yes
    yum: name=* state=latest

  - name: Install development tools
    sudo: yes
    yum: name="@Development tools" state=present

  - name: Install additional dev tools
    sudo: yes
    yum: pkg={{item}} state=latest
    with_items:
      - zlib-devel
      - openssl-devel
      - sqlite-devel
      - bzip2-devel
      - xz-libs

  - name: Download Python 3.4.2
    sudo: yes
    get_url: url="https://www.python.org/ftp/python/3.4.2/Python-3.4.2.tar.xz" dest=~/

  - name: Unarchive Python
    sudo: yes
    unarchive: src=~/Python-3.4.2.tar.xz dest=~/ copy=no

  - name: Configure Python
    sudo: yes
    command: ./configure --prefix=/opt/python3.4.2 chdir=~/Python-3.4.2

  - name: Build and install Python
    sudo: yes
    shell: make && make altinstall chdir=~/Python-3.4.2

  - name: Adding installation location to PATH
    shell: '{{ item }}'
    with_items:
      - echo -e '\n# pyvenv\nPATH=/opt/python3.4.2/bin:$PATH' >> ~/.bashrc
      - source ~/.bashrc

  - name: Create default python environment
    shell: '{{ item }}'
    with_items:
      - cd ~/
      - pyvenv-3.4 py3.4
      - echo 'PATH=~/py3.4/bin:$PATH' >> ~/.bashrc
      - source ~/.bashrc

  - name: Install virtualenvwrapper
    shell: '{{ item }}'
    with_items:
      - pip install virtualenvwrapper
      - mkdir ~/venvs
      - echo -e '\n# virtualenvwrapper\nWORKON_HOME=~/venvs' >> ~/.bashrc
      - echo '. ~/py3.4/bin/virtualenvwrapper.sh' >> ~/.bashrc
      - source ~/.bashrc
