---
  - name: Install nginx.repo
    become: true
    template: src=nginx.repo dest=/etc/yum.repos.d/

  - name: Install Nginx
    sudo: yes
    yum: name=nginx state=latest enablerepo=nginx

  - name: Copy nginx configuration
    sudo: yes
    template: src=nginx.conf dest=/etc/nginx.conf mode=0644

  - name: Stat default.conf
    stat: path=/etc/nginx/conf.d/default.conf
    register: default_config_stat

  - name: Backup default.conf
    sudo: yes
    command: mv /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf.orig
    when: default_config_stat.stat.exists
